services:
  service_mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - pennywise_db:/data/db

  backend:
    build:
      context: ./backend
      target: prod
    restart: unless-stopped
    ports: 
      - "5000:5000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
    links:
      - service_mongo
    depends_on:
      - service_mongo

  frontend:
    build:
      context: ./frontend
      target: runner
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  pennywise_db: {}

