name: Test Penny Wise

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build penny wise and test
      run: |
        cp .env_example .env
        sed -i "s/<db_atlas_user>/${{ secrets.ATLAS_USER }}/g" .env
        sed -i "s/<password>/${{ secrets.ATLAS_PASSWORD }}/g" .env
        sed -i "s/<mongodb_atlas_cluster>/${{ secrets.ATLAS_CLUSTER }}/g" .env
        sed -i "s/_backend_1/-backend-1/g" package.json
        npm install
        npm run start
        until [ `curl -s http://localhost:5000/api/health && [ $? -eq 0 ]` ]; do
            sleep 0.4;
        done
        npm run seed_n_test
